// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSVQ_3oTSfwGZyQXV6pR9rg-r4uzJ8G5U',
    appId: '1:941745899140:web:155cfef29b1309bfee24d1',
    messagingSenderId: '941745899140',
    projectId: 'todo-3d9f9',
    authDomain: 'todo-3d9f9.firebaseapp.com',
    storageBucket: 'todo-3d9f9.appspot.com',
    measurementId: 'G-JE75GNYWH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyHTtf8vt8Jxyv-T7xIStqNmNMYtzXdw',
    appId: '1:941745899140:android:07182644ead5c63aee24d1',
    messagingSenderId: '941745899140',
    projectId: 'todo-3d9f9',
    storageBucket: 'todo-3d9f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqX56Hg7YRzEON89_Z1dTLVrYxld5_Mes',
    appId: '1:941745899140:ios:09d2128107ff5fedee24d1',
    messagingSenderId: '941745899140',
    projectId: 'todo-3d9f9',
    storageBucket: 'todo-3d9f9.appspot.com',
    iosBundleId: 'com.example.node04TodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqX56Hg7YRzEON89_Z1dTLVrYxld5_Mes',
    appId: '1:941745899140:ios:77d2797971f810a4ee24d1',
    messagingSenderId: '941745899140',
    projectId: 'todo-3d9f9',
    storageBucket: 'todo-3d9f9.appspot.com',
    iosBundleId: 'com.example.node04TodoApp.RunnerTests',
  );
}
